$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  modules:
    type: object
    properties:
      wgs_std_viper:
        type: object
        properties:
          url:
            type: string
          tag:
            type: string
        required:
          - url
          - tag
      wgs_somatic_pon:
        type: object
        properties:
          url:
            type: string
          tag:
            type: string
        required:
          - url
          - tag
      wgs_somatic_snp_viper:
        type: object
        properties:
          url:
            type: string
          tag:
            type: string
        required:
          - url
          - tag
      wgs_somatic_cnv_sv_viper:
        type: object
        properties:
          url:
            type: string
          tag:
            type: string
        required:
          - url
          - tag
    required:
      - wgs_std_viper
      - wgs_somatic_snp_viper
      - wgs_somatic_cnv_sv_viper
required:
  - modules
