$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  modules:
    type: object
    properties:
      wgs_std_viper:
        type: string
      wgs_somatic_snp_viper:
        type: string
      wgs_somatic_cnv_sv_viper:
        type: string
    required:
      - wgs_std_viper
      - wgs_somatic_snp_viper
      - wgs_somatic_cnv_sv_viper
  required:
    - modules
  mutect2:
    type: object
    properties:
      panel:
        type: string
    required:
      - panel
  required:
    - mutect2
