$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  workflows:
    type: object
    properties:
      wgs_std_viper:
        type: object
        properties:
          url:
            type: string
          tag:
            type: string
      wgs_somatic_snp_viper:
        type: object
        properties:
          url:
            type: string
          tag:
            type: string
    required:
      - wgs_std_viper
      - wgs_somatic_snp_viper
  required:
    - workflows
